# Generated by Django 5.2.7 on 2025-10-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lastName',
            new_name='first_name',
        ),
        migrations.AlterUniqueTogether(
            name='comments',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='savedpost',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='user',
            name='firstName',
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='likes',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='uniq_like_user_post'),
        ),
        migrations.AddConstraint(
            model_name='savedpost',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='uniq_saved_user_post'),
        ),
    ]
