# Generated by Django 5.2.7 on 2025-10-07 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_rename_lastname_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
