# Generated by Django 5.2.7 on 2025-10-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_rename_first_name_user_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
