# Generated by Django 5.2.7 on 2025-10-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_savedpost'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedpost',
            unique_together={('user', 'post')},
        ),
    ]
